// Common Pakistani cities/towns for spelling validation.
// Fuzzy-matched against customer-entered city so obvious typos are caught,
// while still accepting minor variations.
module.exports = [
  'Lahore', 'Karachi', 'Islamabad', 'Rawalpindi', 'Faisalabad', 'Multan', 'Peshawar', 'Quetta',
  'Sialkot', 'Gujranwala', 'Bahawalpur', 'Sargodha', 'Sukkur', 'Larkana', 'Sheikhupura',
  'Rahim Yar Khan', 'Jhang', 'Gujrat', 'Kasur', 'Mardan', 'Mingora', 'Dera Ghazi Khan', 'Sahiwal',
  'Nawabshah', 'Okara', 'Mirpur Khas', 'Chiniot', 'Kamoke', 'Hafizabad', 'Kohat', 'Jacobabad',
  'Shikarpur', 'Muzaffargarh', 'Khanpur', 'Gojra', 'Mandi Bahauddin', 'Abbottabad', 'Turbat',
  'Dera Ismail Khan', 'Chaman', 'Kot Addu', 'Jaranwala', 'Khairpur', 'Tando Adam', 'Muridke',
  'Jhelum', 'Wah Cantt', 'Kamalia', 'Attock', 'Bahawalnagar', 'Vehari', 'Kabirwala', 'Daska',
  'Mianwali', 'Kot Radha Kishan', 'Toba Tek Singh', 'Pakpattan', 'Chishtian', 'Ahmedpur East',
  'Hasilpur', 'Haroonabad', 'Arifwala', 'Layyah', 'Lodhran', 'Sadiqabad', 'Bhakkar',
  'Nankana Sahib', 'Narowal', 'Khanewal', 'Depalpur', 'Renala Khurd', 'Chichawatni', 'Burewala',
  'Mailsi', 'Faqirwali', 'Fort Abbas', 'Yazman', 'Minchinabad', 'Hujra Shah Muqim', 'Pattoki',
  'Chunian', 'Ferozewala', 'Manga Mandi', 'Raiwind', 'Gujar Khan', 'Kharian', 'Phalia',
  'Malakwal', 'Bhalwal', 'Sillanwali', 'Kot Momin', 'Shahpur', 'Khushab', 'Talagang',
  'Fateh Jang', 'Hassan Abdal', 'Taxila', 'Haripur', 'Mansehra', 'Battagram', 'Shangla', 'Swat',
  'Buner', 'Chitral', 'Dir', 'Nowshera', 'Charsadda', 'Swabi', 'Bannu', 'Lakki Marwat', 'Tank',
  'Karak', 'Hangu', 'Ghotki', 'Kashmore', 'Shahdadkot', 'Dadu', 'Thatta', 'Badin',
  'Tando Muhammad Khan', 'Umerkot', 'Sanghar', 'Naushahro Feroze', 'Matiari', 'Jamshoro',
  'Hyderabad', 'Mirpur', 'Kotli', 'Bhimber', 'Rawalakot', 'Muzaffarabad', 'Bagh', 'Gilgit',
  'Skardu', 'Hunza', 'Sambrial', 'Pasrur', 'Zafarwal', 'Shakargarh', 'Wazirabad', 'Sarai Alamgir',
  'Kamra', 'Nowshera Virkan', 'Khushab', 'Chak Jhumra', 'Samundri', 'Tandlianwala', 'Chak',
];
